# Generated by Django 6.0.5 on 2026-05-30 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='bi-palette', help_text='Bootstrap icon class', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='mobile_fee',
            field=models.DecimalField(decimal_places=0, default=50000, help_text='Biaya tambahan untuk panggilan ke rumah', max_digits=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artists/thumbs/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='short_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='design_reference',
            field=models.ImageField(blank=True, help_text='Upload referensi desain (opsional)', null=True, upload_to='references/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Mahir'), ('master', 'Master')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Tandai sebagai layanan populer'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_label',
            field=models.CharField(default='Mulai dari', help_text="Label harga, mis: 'Mulai dari' / 'Fix price'", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='short_desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='portfolios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='tattoo.artist')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tattoo.service')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='tattoo.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama paket, mis: Small / Medium / Large', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duration', models.CharField(max_length=100)),
                ('is_recommended', models.BooleanField(default=False, help_text='Rekomendasikan paket ini')),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tattoo.service')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tattoo.servicepackage'),
        ),
    ]
