# Generated by Django 6.0.5 on 2026-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0002_servicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Metode pembayaran yang digunakan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('pending', 'Menunggu Pembayaran'), ('paid', 'Lunas'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='snap_token',
            field=models.CharField(blank=True, help_text='Snap token untuk Midtrans', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID transaksi dari payment gateway', max_length=200, null=True),
        ),
    ]
