# Generated by Django 6.0.5 on 2026-06-04 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0003_booking_paid_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_online_payment', models.BooleanField(default=True, help_text='Aktifkan payment gateway untuk pesanan kamu', verbose_name='Terima Pembayaran Online')),
                ('enable_bank_va', models.BooleanField(default=True, verbose_name='Virtual Account Bank')),
                ('enable_ewallet', models.BooleanField(default=True, verbose_name='E-Wallet')),
                ('enable_credit_card', models.BooleanField(default=False, verbose_name='Kartu Kredit / Debit')),
                ('enable_convenience_store', models.BooleanField(default=True, verbose_name='Convenience Store')),
                ('bank_bca_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_bca_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_mandiri_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_mandiri_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_bni_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_bni_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_bri_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_bri_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_permata_number', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_permata_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ewallet_gopay', models.CharField(blank=True, help_text='Nomor HP terdaftar di GoPay', max_length=30, null=True)),
                ('ewallet_ovo', models.CharField(blank=True, help_text='Nomor HP terdaftar di OVO', max_length=30, null=True)),
                ('ewallet_dana', models.CharField(blank=True, help_text='Nomor HP terdaftar di DANA', max_length=30, null=True)),
                ('ewallet_shopeepay', models.CharField(blank=True, max_length=30, null=True)),
                ('ewallet_linkaja', models.CharField(blank=True, max_length=30, null=True)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Biaya layanan tambahan dalam persen (0 = tanpa biaya)', max_digits=5)),
                ('use_split_payment', models.BooleanField(default=False, help_text='Untuk sistem marketplace / bagi hasil otomatis', verbose_name='Gunakan Midtrans Split Payment')),
                ('midtrans_merchant_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Midtrans Sub-Merchant ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='tattoo.artist')),
            ],
        ),
    ]
