# Generated by Django 6.0.5 on 2026-06-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0004_artistpaymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistpaymentsettings',
            name='card_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biaya tambahan yang dibebankan ke customer (contoh: 2.5 untuk 2.5%)', max_digits=5, verbose_name='Biaya Proses Kartu (%)'),
        ),
        migrations.AddField(
            model_name='artistpaymentsettings',
            name='card_note',
            field=models.TextField(blank=True, help_text="Instruksi tambahan untuk customer (misal: 'Tap kartu di studio saat kedatangan')", null=True, verbose_name='Catatan Pembayaran Kartu'),
        ),
        migrations.AddField(
            model_name='artistpaymentsettings',
            name='card_payment_link',
            field=models.URLField(blank=True, help_text='URL payment gateway atau form untuk customer bayar kartu (opsional)', max_length=500, null=True, verbose_name='Link Pembayaran Kartu'),
        ),
        migrations.AddField(
            model_name='artistpaymentsettings',
            name='card_processing_method',
            field=models.CharField(blank=True, choices=[('edc', 'EDC Machine (terminal fisik di studio)'), ('link', 'Payment Link (customer bayar via link)'), ('manual', 'Manual Confirmation (konfirmasi via WhatsApp)')], help_text='Bagaimana customer membayar via kartu', max_length=20, null=True, verbose_name='Metode Proses Kartu'),
        ),
    ]
