# Generated by Django 6.0.5 on 2026-06-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0007_booking_payment_sop'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
