# Generated by Django 6.0.5 on 2026-06-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0008_artist_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='bi-brush', help_text='Bootstrap icon class', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='styles/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('skill_level', models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Mahir'), ('master', 'Master')], default='intermediate', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Gaya utama artist ini')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_styles', to='tattoo.artist')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_styles', to='tattoo.style')),
            ],
            options={
                'ordering': ['-is_primary', '-experience_years'],
                'unique_together': {('artist', 'style')},
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='style_expertise',
            field=models.ManyToManyField(blank=True, related_name='artists', through='tattoo.ArtistStyle', to='tattoo.style'),
        ),
        migrations.AddField(
            model_name='service',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='services', to='tattoo.style'),
        ),
    ]
