# Generated by Django 6.0.5 on 2026-06-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0009_style_artiststyle_artist_style_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_available_mobile',
            field=models.BooleanField(db_index=True, default=True, help_text='Bersedia datang ke lokasi customer', verbose_name='Bisa panggil ke rumah'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_available_studio',
            field=models.BooleanField(db_index=True, default=True, help_text='Melayani di studio', verbose_name='Bisa di studio'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('pending', 'Menunggu Pembayaran'), ('paid', 'Lunas'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('in_progress', 'Sedang Dikerjakan'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False, help_text='Tandai sebagai layanan populer'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
