# Generated by Django 6.0.5 on 2026-07-02 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0010_alter_artist_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['artist', 'status'], name='booking_artist_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='booking_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepackage',
            index=models.Index(fields=['service', 'is_active'], name='pkg_svc_active_idx'),
        ),
    ]
