# Generated by Django 6.0.5 on 2026-07-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0013_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('pending', 'Menunggu Pembayaran'), ('paid', 'Lunas'), ('failed', 'Gagal'), ('refunded', 'Dikembalikan')], default='unpaid', max_length=20),
        ),
    ]
